//-----------------------------------------------------------------------------
// <auto-generated> 
//   This code was generated by a tool. 
// 
//   Changes to this file may cause incorrect behavior and will be lost if  
//   the code is regenerated.
//
//   Tool: AllJoynCodeGenerator.exe
//
//   This tool is located in the Windows 10 SDK and the Windows 10 AllJoyn 
//   Visual Studio Extension in the Visual Studio Gallery.  
//
//   The generated code should be packaged in a Windows 10 C++/CX Runtime  
//   Component which can be consumed in any UWP-supported language using 
//   APIs that are available in Windows.Devices.AllJoyn.
//
//   Using AllJoynCodeGenerator - Invoke the following command with a valid 
//   Introspection XML file and a writable output directory:
//     AllJoynCodeGenerator -i <INPUT XML FILE> -o <OUTPUT DIRECTORY>
// </auto-generated>
//-----------------------------------------------------------------------------
#pragma once

namespace com { namespace microsoft { namespace maker { namespace Blinky {

// This class, and the associated EventArgs classes, exist for the benefit of JavaScript developers who
// do not have the ability to implement IBlinkyService. Instead, BlinkyServiceEventAdapter
// provides the Interface implementation and exposes a set of compatible events to the developer.
public ref class BlinkyServiceEventAdapter sealed : [Windows::Foundation::Metadata::Default] IBlinkyService
{
public:
    // Method Invocation Events
    event Windows::Foundation::TypedEventHandler<BlinkyServiceEventAdapter^, BlinkyStartCalledEventArgs^>^ StartCalled;
    event Windows::Foundation::TypedEventHandler<BlinkyServiceEventAdapter^, BlinkyStopCalledEventArgs^>^ StopCalled;

    // Property Read Events
    event Windows::Foundation::TypedEventHandler<BlinkyServiceEventAdapter^, BlinkyGetVersionRequestedEventArgs^>^ GetVersionRequested;
    event Windows::Foundation::TypedEventHandler<BlinkyServiceEventAdapter^, BlinkyGetBlinkIntervalRequestedEventArgs^>^ GetBlinkIntervalRequested;
    event Windows::Foundation::TypedEventHandler<BlinkyServiceEventAdapter^, BlinkyGetIsBlinkingRequestedEventArgs^>^ GetIsBlinkingRequested;
    
    // Property Write Events
    event Windows::Foundation::TypedEventHandler<BlinkyServiceEventAdapter^, BlinkySetBlinkIntervalRequestedEventArgs^>^ SetBlinkIntervalRequested;

    // IBlinkyService Implementation
    virtual Windows::Foundation::IAsyncOperation<BlinkyStartResult^>^ StartAsync(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ info);
    virtual Windows::Foundation::IAsyncOperation<BlinkyStopResult^>^ StopAsync(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ info);

    virtual Windows::Foundation::IAsyncOperation<BlinkyGetVersionResult^>^ GetVersionAsync(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ info);
    virtual Windows::Foundation::IAsyncOperation<BlinkyGetBlinkIntervalResult^>^ GetBlinkIntervalAsync(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ info);
    virtual Windows::Foundation::IAsyncOperation<BlinkyGetIsBlinkingResult^>^ GetIsBlinkingAsync(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ info);

    virtual Windows::Foundation::IAsyncOperation<BlinkySetBlinkIntervalResult^>^ SetBlinkIntervalAsync(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ info, _In_ double value);
};

} } } } 
